const save=()=>{localStorage.setItem(KEYS.products,JSON.stringify(products));localStorage.setItem(KEYS.favorites,JSON.stringify(favorites));localStorage.setItem(KEYS.candidates,JSON.stringify(candidates));localStorage.setItem(KEYS.clicks,JSON.stringify(clicks));};
function freshnessDays(p){return Math.floor((Date.now()-new Date(p.updatedAt||0).getTime())/86400000)}
function dealScore(p){const d=pct(p.price,p.normalPrice), hist=p.medianPrice>0?Math.max(0,(p.medianPrice-p.price)/p.medianPrice*100):0, shippingPenalty=p.shipping>0?Math.min(12,p.shipping/1000*3):0, obs=Math.min(20,(p.observedDays||0)*1.4), freshness=Math.max(0,15-freshnessDays(p)*2.5);return Math.max(0,Math.min(100,Math.round(d*.85+hist*1.05+obs+freshness-shippingPenalty)))}
function confidence(p){if(freshnessDays(p)>7)return ['확인 필요','오래된 데이터'];if((p.observedDays||0)<3)return ['잠정','가격 데이터 부족'];if(dealScore(p)>=75)return ['강력 특가','가격 메리트 높음'];if(dealScore(p)>=55)return ['특가 후보','비교 가치 있음'];if(dealScore(p)>=35)return ['관찰','추가 확인 권장'];return ['보통','메리트 제한적']}
function effectivePrice(p){return Number(p.price||0)+Number(p.shipping||0)}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
function renderCategories(){const row=document.getElementById('categoryRow');row.innerHTML=categories.map(c=>`<button class="category-chip ${state.category===c?'active':''}" data-cat="${c}">${c}</button>`).join('');row.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderAll()})}
function filteredProducts(list=products){let a=[...list].filter(p=>{const q=state.query.trim().toLowerCase();const matchQ=!q||[p.name,p.source,p.category].some(v=>(v||'').toLowerCase().includes(q));const matchCat=state.category==='전체'||p.category===state.category;const score=dealScore(p);let matchQuick=true;if(state.quick==='hot')matchQuick=score>=75;if(state.quick==='fresh')matchQuick=freshnessDays(p)<=1;if(state.quick==='discount')matchQuick=pct(p.price,p.normalPrice)>=20;if(state.quick==='watch')matchQuick=score>=35&&score<75;return matchQ&&matchCat&&matchQuick});a.sort((x,y)=>state.sort==='priceAsc'?effectivePrice(x)-effectivePrice(y):state.sort==='discount'?pct(y.price,y.normalPrice)-pct(x.price,x.normalPrice):state.sort==='fresh'?new Date(y.updatedAt)-new Date(x.updatedAt):dealScore(y)-dealScore(x));return a}
function dealCard(p){const [label,why]=confidence(p), score=dealScore(p), discount=pct(p.price,p.normalPrice), fav=favorites.includes(p.id), stale=freshnessDays(p)>7;return `<article class="deal-card" data-id="${p.id}"><div><div class="deal-meta"><span class="pill ${score>=75?'hot':''}">${label}</span><span>${p.source}</span><span>·</span><span>${p.category}</span>${stale?'<span class="pill">업데이트 필요</span>':''}</div><div class="deal-title">${escapeHtml(p.name)}</div><div class="price-row"><strong>${money(effectivePrice(p))}</strong>${p.normalPrice?`<span class="normal-price">${money(p.normalPrice)}</span>`:''}${discount?`<span class="discount">${discount}%↓</span>`:''}</div><div class="deal-sub">${p.shipping?`배송비 ${money(p.shipping)} 포함`:'무료배송/배송비 0원 입력'} · ${why} · 관측 ${p.observedDays||0}일</div></div><div class="deal-actions"><div class="score"><div><strong>${score}</strong><small>오혜야 점수</small></div></div><button class="fav-btn ${fav?'active':''}" data-fav="${p.id}" aria-label="찜">${fav?'♥':'♡'}</button></div></article>`}
function bindDealCards(scope=document){scope.querySelectorAll('.deal-card').forEach(card=>card.onclick=e=>{if(e.target.closest('[data-fav]'))return;openDetail(card.dataset.id)});scope.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(b.dataset.fav)})}
function renderDeals(){const list=filteredProducts();document.getElementById('dealCount').textContent=list.length;document.getElementById('heroStat').innerHTML=`<strong>${products.filter(p=>freshnessDays(p)<=7).length}</strong><span>검토 가능한 상품</span>`;const el=document.getElementById('dealList');el.innerHTML=list.map(dealCard).join('');document.getElementById('emptyState').classList.toggle('hidden',list.length>0);bindDealCards(el)}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save();renderDeals();renderFavorites();toast(favorites.includes(id)?'찜에 저장했어요':'찜에서 뺐어요')}
function renderFavorites(){const arr=products.filter(p=>favorites.includes(p.id));const el=document.getElementById('favoriteList');el.innerHTML=arr.map(dealCard).join('');document.getElementById('favoriteEmpty').classList.toggle('hidden',arr.length>0);bindDealCards(el)}
function openDetail(id){const p=products.find(x=>x.id===id);if(!p)return;const score=dealScore(p),[label,why]=confidence(p),link=p.affiliateUrl||p.url;document.getElementById('detailContent').innerHTML=`<div class="detail-score">오혜야 ${score} · ${label}</div><div class="detail-title">${escapeHtml(p.name)}</div><div class="deal-meta">${escapeHtml(p.source)} · ${escapeHtml(p.category)} · ${new Date(p.updatedAt).toLocaleDateString('ko-KR')} 업데이트</div><div class="detail-price">${money(effectivePrice(p))}</div><div class="detail-grid"><div class="detail-cell"><small>현재 상품가</small><strong>${money(p.price)}</strong></div><div class="detail-cell"><small>기준가</small><strong>${p.normalPrice?money(p.normalPrice):'미입력'}</strong></div><div class="detail-cell"><small>과거 대표가</small><strong>${p.medianPrice?money(p.medianPrice):'미입력'}</strong></div><div class="detail-cell"><small>관측</small><strong>${p.observedDays||0}일</strong></div></div><div class="detail-note"><strong>${why}</strong><br>${escapeHtml(p.note||'구매 전 실제 판매 페이지의 최종 가격과 배송 조건을 확인하세요.')}</div><div class="detail-cta"><button class="secondary-btn" onclick="window.toggleFavorite('${p.id}')">${favorites.includes(p.id)?'♥ 찜 해제':'♡ 찜하기'}</button>${link?`<a class="primary-btn" href="${escapeAttr(link)}" target="_blank" rel="noopener sponsored" onclick="window.trackClick('${p.id}')">판매처 보기</a>`:'<button class="primary-btn" disabled>링크 미등록</button>'}</div>`;document.getElementById('detailDialog').showModal()}
window.toggleFavorite=id=>{toggleFavorite(id);document.getElementById('detailDialog').close()};window.trackClick=id=>{clicks[id]=(clicks[id]||0)+1;save()};
function renderAdmin(){const fresh=products.filter(p=>freshnessDays(p)<=7).length, hot=products.filter(p=>dealScore(p)>=75&&freshnessDays(p)<=7).length, pending=candidates.filter(c=>c.status==='pending').length,totalClicks=Object.values(clicks).reduce((a,b)=>a+b,0);document.getElementById('adminStats').innerHTML=[[products.length,'전체 상품'],[fresh,'최신 데이터'],[hot,'강력 특가'],[pending,'대기 후보']].map(([v,l])=>`<div class="stat-card"><strong>${v}</strong><span>${l}</span></div>`).join('')+`<div class="stat-card"><strong>${totalClicks}</strong><span>누적 이동 클릭</span></div>`;
const list=document.getElementById('adminProductList');list.innerHTML=products.map(p=>`<div class="admin-row"><div><h3>${escapeHtml(p.name)}</h3><p>${p.source} · ${money(effectivePrice(p))} · 점수 ${dealScore(p)} · ${new Date(p.updatedAt).toLocaleDateString('ko-KR')}</p></div><div class="row-actions"><button data-edit="${p.id}">수정</button><button data-delete="${p.id}">삭제</button></div></div>`).join('');list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProductForm(b.dataset.edit));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('이 상품을 삭제할까요?')){products=products.filter(p=>p.id!==b.dataset.delete);favorites=favorites.filter(x=>x!==b.dataset.delete);save();renderAll();toast('삭제했어요')}});renderCandidates()}
function renderCandidates(){const el=document.getElementById('candidateList');const arr=candidates.filter(c=>c.status!=='excluded');el.innerHTML=arr.length?arr.map(c=>`<div class="admin-row"><div><h3>${escapeHtml(c.name)}</h3><p>${c.source} · ${money(c.price)}${c.normalPrice?` · 기준가 ${money(c.normalPrice)}`:''} · ${c.status==='pending'?'검토 대기':'보류'}</p></div><div class="row-actions"><button data-approve="${c.id}">승인</button><button data-hold="${c.id}">보류</button><button data-exclude="${c.id}">제외</button></div></div>`).join(''):'<div class="empty-state"><strong>대기 후보가 없습니다.</strong></div>';el.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approveCandidate(b.dataset.approve));el.querySelectorAll('[data-hold]').forEach(b=>b.onclick=()=>setCandidateStatus(b.dataset.hold,'hold'));el.querySelectorAll('[data-exclude]').forEach(b=>b.onclick=()=>setCandidateStatus(b.dataset.exclude,'excluded'))}
